task 19
pavels3579/rack2 pull request #1
Opened 2019-03-25 06:52 UTC by pavels3579

Rack interface

2019-03-26 04:36 UTC, iBublik requested changes

2019-03-26 04:36 UTC, iBublik commented on app.rb
> +  STATUS_LIST = {
Не понял для чего нужен этот хэш, он ведь никакой семантики не добавляет. Проще сразу писать статус 200/400/404

2019-03-26 04:36 UTC, iBublik commented on app.rb
> +    if env["REQUEST_PATH"] != '/time'
Можно использовать объект Rack::Request, чтоб не работать с env как с хэшом

2019-03-26 04:36 UTC, iBublik commented on app.rb
> +      return [status, headers, body(body_str)]
Сделай метод `make_response(status, headers, body)`, который будет формировать ответ. Код станет компактнее

2019-03-26 04:36 UTC, iBublik commented on app.rb
> +    if env["QUERY_STRING"][0, 7] != 'format='
Нельзя полагаться на позицию строки, это слишком хрупко. Тут уже явно напрашивается Rack::Request

2019-03-26 04:36 UTC, iBublik commented on app.rb
> +    t = Time.now
Создай отдельный класс, который будет заниматься исключительно логикой - форматированием времени. Базовый интерфейс - валидны ли параметры, отформатированное время и список невалидных параметров. Это уже можно использовать в App

2019-03-26 04:36 UTC, iBublik commented on app.rb
> +        result << t.year.to_s
Для форматирования времени лучше использовать `strftime`. Избавишься от этой лесенки условий

2019-03-27 06:30 UTC, iBublik requested changes

2019-03-27 06:30 UTC, iBublik commented on format_time.rb
> +  def get_response
У тебя перемешалась бизнес-логика и http специфака. Лучше их полностью разделить - FormatTime пусть занимается исключительно бизнес-логикой, а App - всей http кухней

2019-03-27 06:30 UTC, iBublik commented on format_time.rb
> +    time_array.each do |f|
Смотри, у тебя есть массив форматов, тебе нужно получить валидные и невалидные форматы. Есть метод `partition`, который разделяет коллекцию на 2 массива - он будет очень полезен

2019-03-27 06:30 UTC, iBublik commented on format_time.rb
> +        result << t.strftime(TIME_FORMAT[f.to_sym])
Сначала собери итоговый формат, потом 1 раз вызови strftime

2019-03-27 06:30 UTC, iBublik commented on format_time.rb
> +  def get_body(str)
Особого смысла в этом методе нет, это можно сразу в `make_response` сделать

2019-03-28 05:18 UTC, iBublik requested changes

2019-03-28 05:18 UTC, iBublik commented on format_time.rb
> +  def valid_url?
Идея в том, что твой класс вообще не должен знать, что используется в веб-приложении. Поэтому все эти проверки - не его ответственность. Он должен получить на вход список форматов и обработать их

2019-03-28 05:18 UTC, iBublik commented on format_time.rb
> +    res = time_array.partition { |f| !TIME_FORMAT[f.to_sym].nil? }
```suggestion
    res = time_array.partition { |format| TIME_FORMAT.key?[format.to_sym] }
```

2019-03-28 05:18 UTC, iBublik commented on format_time.rb
> +    correct.each { |f| result << TIME_FORMAT[f.to_sym] }
Для преобразования одной коллекции в другую используй `map`

2019-03-28 05:18 UTC, iBublik commented on format_time.rb
> +    return { status: 200, body: result, valid: true }
Не надо все в 1 метод пихать. Создай 3 метода - валидны ли форматы, список невалидных форматов и отформатированное время

2019-03-29 14:41 UTC, iBublik approved these changes

2019-03-29 14:41 UTC, iBublik commented on format_time.rb
> +    correct = valid_formats.map { |format| TIME_FORMAT[format.to_sym]}
```suggestion
    correct = valid_formats.map { |format| TIME_FORMAT[format.to_sym] }
```

2019-03-29 14:41 UTC, iBublik commented on format_time.rb
> +    @formats.select { |format| TIME_FORMAT.key?(format.to_sym) }
Можно сразу в конструкторе разбить параметры `@valid_formats, @invalid_formats = formats.partition { |format| TIME_FORMAT.key?(format.to_sym) }`

2019-03-29 20:43 UTC, pavels3579 commented on format_time.rb
> +    @formats.select { |format| TIME_FORMAT.key?(format.to_sym) }
Спасибо! Сделал.

2019-03-29 20:43 UTC, merged